version: '3.8'

services:
  apartment-helper-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: apartment-helper
      POSTGRES_USER: apartment-helper
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"