name: CI

on: [pull_request]

defaults:
  run:
    working-directory: ./apartment-helper-app

jobs:
  lint:
    runs-on: [ubuntu-latest]
    name: Lint and Format

    strategy:
      matrix:
        node_version: [20.5.1]
  
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint
   